# Generated by Django 4.2.6 on 2023-10-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_unlike',
            new_name='post_dislike',
        ),
    ]
