# Generated by Django 4.2.6 on 2023-10-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_post_dislike_remove_post_post_like_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='like_creation',
            field=models.DateTimeField(auto_now_add=True, default='2000-01-01'),
            preserve_default=False,
        ),
    ]
